import type { StorefrontProduct } from '@/lib/types/product';
import { LOCAL_IMAGES } from '@/lib/images';

export const CURATED_FALLBACK_PRODUCTS: StorefrontProduct[] = [
  // Bedroom Collection
  {
    id: 'prod-bed-1',
    name: 'Royal Solid Sheesham King Bed',
    description: 'Handcrafted master king-size bed made from seasoned solid Sheesham with hand-carved floral crown details and velvet upholstered headboard.',
    price: 245000,
    category: 'Bedroom',
    image: LOCAL_IMAGES.bed,
    material: '100% Solid Sheesham Wood',
    dimensions: '78" x 84" x 54"',
    stockCount: 5,
    isPremium: true,
    avgRating: 4.9,
    reviewCount: 28,
  },
  {
    id: 'prod-bed-2',
    name: 'Imperial Walnut Upholstered Bed Set',
    description: 'Contemporary luxury bed frame finished in deep walnut lacquer with champagne gold accents and matching dual nightstands.',
    price: 310000,
    category: 'Bedroom',
    image: LOCAL_IMAGES.bed,
    material: 'Seasoned Walnut & Velvet',
    dimensions: '80" x 86" x 58"',
    stockCount: 4,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 19,
  },
  {
    id: 'prod-bed-3',
    name: 'Emerald Tufted High-Back Master Bed',
    description: 'Statement master bed featuring bespoke emerald green velvet tufting with reinforced solid timber structure.',
    price: 275000,
    category: 'Bedroom',
    image: LOCAL_IMAGES.bed,
    material: 'Solid Wood & Royal Velvet',
    dimensions: '76" x 82" x 62"',
    stockCount: 3,
    isPremium: true,
    avgRating: 4.8,
    reviewCount: 14,
  },

  // Living Room / Sofas Collection
  {
    id: 'prod-sofa-1',
    name: 'Imperial Turkish Velvet Chesterfield Sofa',
    description: 'Masterpiece 3-seater sofa in Turkish champagne velvet with deep button tufting and solid hand-turned hardwood legs.',
    price: 195000,
    category: 'Living Room',
    image: LOCAL_IMAGES.sofa,
    material: 'Turkish Velvet & Hardwood',
    dimensions: '90" x 38" x 34"',
    stockCount: 6,
    isPremium: true,
    avgRating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'prod-sofa-2',
    name: 'Royal Curved Architectural Sectional',
    description: 'Curved modern silhouette sofa tailored for expansive luxury living spaces with high-density ergonomic cushioning.',
    price: 385000,
    category: 'Living Room',
    image: LOCAL_IMAGES.sofa,
    material: 'Premium Bouclé & Walnut',
    dimensions: '120" x 65" x 32"',
    stockCount: 2,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 31,
  },

  // Dining Room Collection
  {
    id: 'prod-dining-1',
    name: 'Royal Sheesham 8-Seater Dining Set',
    description: 'Handcrafted solid Sheesham dining table with 8 ergonomically contoured dining chairs in champagne velvet upholstery.',
    price: 360000,
    category: 'Dining Room',
    image: LOCAL_IMAGES.dining,
    material: 'Solid Sheesham Wood',
    dimensions: '96" x 44" x 30"',
    stockCount: 3,
    isPremium: true,
    avgRating: 4.9,
    reviewCount: 23,
  },

  // Wardrobes Collection
  {
    id: 'prod-wardrobe-1',
    name: 'Imperial 4-Door Solid Sheesham Wardrobe',
    description: 'Architectural luxury wardrobe with soft-close German hinges, interior LED illumination, and custom velvet-lined jewelry drawers.',
    price: 420000,
    category: 'Wardrobes',
    image: LOCAL_IMAGES.wardrobe,
    material: '100% Solid Sheesham Wood',
    dimensions: '84" x 24" x 90"',
    stockCount: 2,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 17,
  },

  // Coffee Tables Collection
  {
    id: 'prod-coffee-1',
    name: 'Luxe Italian Marble & Sheesham Coffee Table',
    description: 'Hand-honed Calacatta gold marble top resting on a sculptural solid Sheesham wood base with brushed brass trim.',
    price: 85000,
    category: 'Coffee Tables',
    image: LOCAL_IMAGES.sofa,
    material: 'Calacatta Marble & Sheesham',
    dimensions: '48" x 28" x 18"',
    stockCount: 8,
    isPremium: true,
    avgRating: 4.8,
    reviewCount: 35,
  },
];
