import type { StorefrontProduct } from '@/lib/types/product';

export const CURATED_FALLBACK_PRODUCTS: StorefrontProduct[] = [
  {
    id: 'prod-sofa-1',
    name: 'Imperial Chesterfield Solid Sheesham Sofa Set',
    description: '100% Solid Seasoned Sheesham Wood frame with royal velvet tufting and 10-year termite warranty.',
    price: 385000,
    category: 'Living Room',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Sheesham Wood & Velvet',
    dimensions: '3-Seater: 84x36x34 in, 2-Seater: 64x36x34 in',
    stockCount: 8,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 42,
  },
  {
    id: 'prod-bed-1',
    name: 'Royal Sheesham King Bed Set with Tufted Velvet Headboard',
    description: 'King size solid rosewood master bed with hydraulic under-bed storage and 2 matching nightstands.',
    price: 295000,
    category: 'Bedroom',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Sheesham Rosewood',
    dimensions: '78 x 72 x 54 in (King Size)',
    stockCount: 6,
    isPremium: true,
    avgRating: 4.9,
    reviewCount: 38,
  },
  {
    id: 'prod-dining-1',
    name: 'Sultan Handcrafted 8-Seater Solid Sheesham Dining Set',
    description: 'Hand-carved 8-seater dining table with tempered glass top and 8 cushioned high-back chairs.',
    price: 245000,
    category: 'Dining Room',
    image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Seasoned Sheesham Wood',
    dimensions: '96 x 42 x 30 in (Table)',
    stockCount: 4,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 29,
  },
  {
    id: 'prod-sofa-2',
    name: 'Karachi Contemporary L-Shape Modular Sectional Sofa',
    description: 'Modern luxury corner sofa with high-resilience foam cushioning and stain-resistant fabric.',
    price: 245000,
    category: 'Living Room',
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Wood & Stain-Resistant Chenille',
    dimensions: '110 x 85 x 33 in',
    stockCount: 10,
    isPremium: true,
    avgRating: 4.8,
    reviewCount: 24,
  },
  {
    id: 'prod-wardrobe-1',
    name: 'Maharani 4-Door Solid Wood Luxury Wardrobe',
    description: 'Heavy-duty 4-door wardrobe with built-in locker, velvet jewelry drawers, and antique brass handles.',
    price: 195000,
    category: 'Luxury Wardrobes',
    image: 'https://images.unsplash.com/photo-1595514535415-eb942f2ed805?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Sheesham & Walnut Veneer',
    dimensions: '84 x 72 x 24 in',
    stockCount: 5,
    isPremium: true,
    avgRating: 4.9,
    reviewCount: 19,
  },
  {
    id: 'prod-table-1',
    name: 'Italian Marble Top Designer Center Table',
    description: 'Natural Carrara white marble top with brass gold electroplated steel base.',
    price: 125000,
    category: 'Center tables',
    image: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Natural Marble & Gold Steel',
    dimensions: '48 x 24 x 18 in',
    stockCount: 12,
    isPremium: false,
    avgRating: 5.0,
    reviewCount: 31,
  },
  {
    id: 'prod-chair-1',
    name: 'Islamabad Luxury Leather Recliner Armchair',
    description: 'Ergonomic genuine leather armchair with 360-degree swivel and 3-stage recline mechanism.',
    price: 115000,
    category: 'Coffee Chairs',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Genuine Top-Grain Leather',
    dimensions: '38 x 36 x 40 in',
    stockCount: 7,
    isPremium: false,
    avgRating: 4.8,
    reviewCount: 16,
  },
  {
    id: 'prod-office-1',
    name: 'Executive Dark Walnut Office Workstation Desk',
    description: 'Executive director desk with wireless charging pad, wire management, and locking file cabinet.',
    price: 165000,
    category: 'Custom Furniture Solutions',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Walnut & Sheesham',
    dimensions: '72 x 36 x 30 in',
    stockCount: 6,
    isPremium: true,
    avgRating: 5.0,
    reviewCount: 12,
  },
  {
    id: 'prod-tv-1',
    name: 'Modern Floating Sheesham TV Console Unit',
    description: 'Wall-mounted 75-inch TV entertainment unit with ambient LED backlight channels.',
    price: 85000,
    category: 'TV Units',
    image: 'https://images.unsplash.com/photo-1593696140826-c58b021acf8b?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Solid Sheesham Wood',
    dimensions: '78 x 16 x 14 in',
    stockCount: 9,
    isPremium: false,
    avgRating: 4.7,
    reviewCount: 22,
  },
  {
    id: 'prod-mirror-1',
    name: 'Full-Length Carved Sheesham Royal Floor Mirror',
    description: 'Hand-carved Baroque style dressing mirror with 5mm distortion-free silver glass.',
    price: 48000,
    category: 'Long Mirors',
    image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&fm=webp&w=380&q=55',
    material: 'Carved Sheesham & Silver Glass',
    dimensions: '72 x 30 in',
    stockCount: 15,
    isPremium: false,
    avgRating: 4.9,
    reviewCount: 17,
  },
];
